apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dlz03asru-nodejs
  janus-idp.io/tekton: dlz03asru-nodejs
  backstage.io/kubernetes-id: dlz03asru-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dlz03asru-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
